spring:
  spring.application.name: Universidad
  jpa.hibernate.ddl-auto: update
  spring.jpa.hibernate.ddl-auto: validate
  datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/universidad?createDatabaseIfNotExist=true
   username: root
   password: 1234

   hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
server:
    port: 8081
logging:
    level:
         root: INFO
    file:
         name: C:\logs\Issues.log
         max-size: 1MB
         max-history: 10
         total-size-cap: 10MB
